export const state = {
  currentItem: 'openclaw',
  sessions: [],
  currentSessionKey: 'default',
  projects: [],
  tabs: {},
  activeTab: {},
  dragTabState: { projectId: null, tabId: null },
  dragProjectState: { projectId: null },
  tabRenameState: { projectId: null, tabId: null },
  projectTerminalState: {},
  projectLastSeenAt: {},
  terminalSearchVisible: false,
  terminalTheme: 'dark',
  unreadCount: 0,
};
